// This file was generated by generate.py

#include "Metadata.h"

static const char* const names[] = {
    "Model",
    "Serial Number",
    "Hardware Version",
    "Bootloader Version",
    "Firmware Version",
    "Device Name",
    "Binary Mode",
};

static const char* const keys[] = {
    "model",
    "serial_number",
    "hardware_version",
    "bootloader_version",
    "firmware_version",
    "device_name",
    "binary_mode",
};

const MetadataType types[] = {
    MetadataTypeString,
    MetadataTypeString,
    MetadataTypeString,
    MetadataTypeString,
    MetadataTypeString,
    MetadataTypeString,
    MetadataTypeBool,
};

const size_t sizes[] = {
    sizeof (((Ximu3SettingsValues *) 0)->model),
    sizeof (((Ximu3SettingsValues *) 0)->serialNumber),
    sizeof (((Ximu3SettingsValues *) 0)->hardwareVersion),
    sizeof (((Ximu3SettingsValues *) 0)->bootloaderVersion),
    sizeof (((Ximu3SettingsValues *) 0)->firmwareVersion),
    sizeof (((Ximu3SettingsValues *) 0)->deviceName),
    sizeof (((Ximu3SettingsValues *) 0)->binaryMode),
};

const void* const defaults[] = {
    (void*) (&(char[32]) {"Twintig Pad Pads"}),
    (void*) (&(char[32]) {"Unknown"}),
    (void*) (&(char[32]) {"Unknown"}),
    (void*) (&(char[32]) {"Unknown"}),
    (void*) (&(char[32]) {"Unknown"}),
    (void*) (&(char[32]) {"Twintig Tap Pads"}),
    (void*) (&(bool) {true}),
};

const bool preserveds[] = {
    true,
    true,
    true,
    true,
    false,
    false,
    false,
};

const bool readOnlys[] = {
    true,
    true,
    true,
    true,
    true,
    false,
    false,
};

static void* GetValue(Ximu3Settings * const settings, const Ximu3SettingsIndex index) {
    switch (index) {
        case Ximu3SettingsIndexModel:
            return &settings->values.model;
        case Ximu3SettingsIndexSerialNumber:
            return &settings->values.serialNumber;
        case Ximu3SettingsIndexHardwareVersion:
            return &settings->values.hardwareVersion;
        case Ximu3SettingsIndexBootloaderVersion:
            return &settings->values.bootloaderVersion;
        case Ximu3SettingsIndexFirmwareVersion:
            return &settings->values.firmwareVersion;
        case Ximu3SettingsIndexDeviceName:
            return &settings->values.deviceName;
        case Ximu3SettingsIndexBinaryMode:
            return &settings->values.binaryMode;

    }
    return NULL; // avoid compiler warning
}

Metadata MetadataGet(Ximu3Settings * const settings, const Ximu3SettingsIndex index) {
    const Metadata metadata = {
        .name = names[index],
        .key = keys[index],
        .value = GetValue(settings, index),
        .type = types[index],
        .size = sizes[index],
        .defaultValue = defaults[index],
        .preserved = preserveds[index],
        .readOnly = readOnlys[index],
        .applied = &settings->applied[index],
    };
    return metadata;
}
