// This file was generated by generate.py

#include "Metadata.h"

static const char* const names[] = {
    "Serial Number",
    "Hardware Version",
    "Firmware Version",
    "Device Name",
    "High-pass Filter",
    "Threshold",
    "Holdoff",
    "Send ADC Data",
    "Binary Mode",
};

static const char* const keys[] = {
    "serial_number",
    "hardware_version",
    "firmware_version",
    "device_name",
    "high_pass_filter",
    "threshold",
    "holdoff",
    "send_adc_data",
    "binary_mode",
};

const MetadataType types[] = {
    MetadataTypeString,
    MetadataTypeString,
    MetadataTypeString,
    MetadataTypeString,
    MetadataTypeBool,
    MetadataTypeFloat,
    MetadataTypeUint32,
    MetadataTypeBool,
    MetadataTypeBool,
};

const size_t sizes[] = {
    sizeof (((Ximu3SettingsValues *) 0)->serialNumber),
    sizeof (((Ximu3SettingsValues *) 0)->hardwareVersion),
    sizeof (((Ximu3SettingsValues *) 0)->firmwareVersion),
    sizeof (((Ximu3SettingsValues *) 0)->deviceName),
    sizeof (((Ximu3SettingsValues *) 0)->highPassFilter),
    sizeof (((Ximu3SettingsValues *) 0)->threshold),
    sizeof (((Ximu3SettingsValues *) 0)->holdoff),
    sizeof (((Ximu3SettingsValues *) 0)->sendAdcData),
    sizeof (((Ximu3SettingsValues *) 0)->binaryMode),
};

const void* const defaults[] = {
    (void*) (&(char[32]) {"Unknown"}),
    (void*) (&(char[16]) {"Unknown"}),
    (void*) (&(char[32]) {"Unknown"}),
    (void*) (&(char[32]) {"Twintig Tap Pads"}),
    (void*) (&(bool) {true}),
    (void*) (&(float) {-0.02f}),
    (void*) (&(uint32_t) {250}),
    (void*) (&(bool) {true}),
    (void*) (&(bool) {true}),
};

const bool preserveds[] = {
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
};

const bool readOnlys[] = {
    true,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
};

static void* GetValue(Ximu3Settings * const settings, const Ximu3SettingsIndex index) {
    switch (index) {
        case Ximu3SettingsIndexSerialNumber:
            return &settings->values.serialNumber;
        case Ximu3SettingsIndexHardwareVersion:
            return &settings->values.hardwareVersion;
        case Ximu3SettingsIndexFirmwareVersion:
            return &settings->values.firmwareVersion;
        case Ximu3SettingsIndexDeviceName:
            return &settings->values.deviceName;
        case Ximu3SettingsIndexHighPassFilter:
            return &settings->values.highPassFilter;
        case Ximu3SettingsIndexThreshold:
            return &settings->values.threshold;
        case Ximu3SettingsIndexHoldoff:
            return &settings->values.holdoff;
        case Ximu3SettingsIndexSendAdcData:
            return &settings->values.sendAdcData;
        case Ximu3SettingsIndexBinaryMode:
            return &settings->values.binaryMode;

    }
    return NULL; // avoid compiler warning
}

Metadata MetadataGet(Ximu3Settings * const settings, const Ximu3SettingsIndex index) {
    const Metadata metadata = {
        .name = names[index],
        .key = keys[index],
        .value = GetValue(settings, index),
        .type = types[index],
        .size = sizes[index],
        .defaultValue = defaults[index],
        .preserved = preserveds[index],
        .readOnly = readOnlys[index],
        .applied = &settings->applied[index],
    };
    return metadata;
}
