// This file was generated by generate.py

#include "Ximu3Definitions.h"

Ximu3Result Ximu3SettingsIndexFrom(Ximu3SettingsIndex * const index, const int integer) {
    switch (integer) {
        case Ximu3SettingsIndexModel:
            *index = Ximu3SettingsIndexModel;
            break;
        case Ximu3SettingsIndexSerialNumber:
            *index = Ximu3SettingsIndexSerialNumber;
            break;
        case Ximu3SettingsIndexHardwareVersion:
            *index = Ximu3SettingsIndexHardwareVersion;
            break;
        case Ximu3SettingsIndexBootloaderVersion:
            *index = Ximu3SettingsIndexBootloaderVersion;
            break;
        case Ximu3SettingsIndexFirmwareVersion:
            *index = Ximu3SettingsIndexFirmwareVersion;
            break;
        case Ximu3SettingsIndexDeviceName:
            *index = Ximu3SettingsIndexDeviceName;
            break;
        case Ximu3SettingsIndexHighPassFilter:
            *index = Ximu3SettingsIndexHighPassFilter;
            break;
        case Ximu3SettingsIndexThreshold:
            *index = Ximu3SettingsIndexThreshold;
            break;
        case Ximu3SettingsIndexHoldoff:
            *index = Ximu3SettingsIndexHoldoff;
            break;
        case Ximu3SettingsIndexSendAdcData:
            *index = Ximu3SettingsIndexSendAdcData;
            break;
        case Ximu3SettingsIndexBinaryMode:
            *index = Ximu3SettingsIndexBinaryMode;
            break;
        default:
            return Ximu3ResultError;
    }
    return Ximu3ResultOk;
}
