// This file was generated by generate.py

#ifndef XIMU3_DEFINITIONS_H
#define XIMU3_DEFINITIONS_H

#include <stdbool.h>
#include <stdint.h>

#define XIMU3_MAX_KEY_LENGTH (18)

#define XIMU3_NUMBER_OF_SETTINGS (11)

#define XIMU3_TERMINATION '\n'

#define XIMU3_TERMINATION_STRING "\n"

#define XIMU3_MUX_ID '^'

#define XIMU3_MUX_BROADCAST XIMU3_MUX_ID

typedef enum {
    Ximu3ResultOk,
    Ximu3ResultError,
} Ximu3Result;

typedef struct {
    char model[32];
    char serialNumber[32];
    char hardwareVersion[32];
    char bootloaderVersion[32];
    char firmwareVersion[32];
    char deviceName[32];
    bool highPassFilter;
    float threshold;
    uint32_t holdoff;
    bool sendAdcData;
    bool binaryMode;
} Ximu3SettingsValues;

typedef enum {
    Ximu3SettingsIndexModel,
    Ximu3SettingsIndexSerialNumber,
    Ximu3SettingsIndexHardwareVersion,
    Ximu3SettingsIndexBootloaderVersion,
    Ximu3SettingsIndexFirmwareVersion,
    Ximu3SettingsIndexDeviceName,
    Ximu3SettingsIndexHighPassFilter,
    Ximu3SettingsIndexThreshold,
    Ximu3SettingsIndexHoldoff,
    Ximu3SettingsIndexSendAdcData,
    Ximu3SettingsIndexBinaryMode,
} Ximu3SettingsIndex;

Ximu3Result Ximu3SettingsIndexFrom(Ximu3SettingsIndex * const index, const int integer);

#endif
