// This file was generated by generate.py

#ifndef XIMU3_DEFINITIONS_H
#define XIMU3_DEFINITIONS_H

#include <stdbool.h>
#include <stdint.h>

#define XIMU3_READ_SIZE 2048

#define XIMU3_KEY_SIZE 64

#define XIMU3_VALUE_SIZE 512

#define XIMU3_OBJECT_SIZE 1024

#define XIMU3_MAX_KEY_LENGTH 16

#define XIMU3_NUMBER_OF_SETTINGS 9

#define XIMU3_MUX_HEADER_SIZE 2

typedef enum {
    Ximu3ResultOk,
    Ximu3ResultError,
} Ximu3Result;

typedef struct {
    char serialNumber[32];
    char hardwareVersion[16];
    char firmwareVersion[32];
    char deviceName[32];
    bool highPassFilter;
    float threshold;
    uint32_t holdoff;
    bool sendAdcData;
    bool binaryMode;
} Ximu3SettingsValues;

typedef enum {
    Ximu3SettingsIndexSerialNumber,
    Ximu3SettingsIndexHardwareVersion,
    Ximu3SettingsIndexFirmwareVersion,
    Ximu3SettingsIndexDeviceName,
    Ximu3SettingsIndexHighPassFilter,
    Ximu3SettingsIndexThreshold,
    Ximu3SettingsIndexHoldoff,
    Ximu3SettingsIndexSendAdcData,
    Ximu3SettingsIndexBinaryMode,
} Ximu3SettingsIndex;

Ximu3Result Ximu3SettingsIndexFrom(Ximu3SettingsIndex * const index, const int integer);

#endif
